### ISSUE TITLE
Very small addition in multi-tenancy docs

### ISSUE THREAD

**Issue by danceb** [qwc-services/qwc-services.github.io#19]
Within the docs for multi tenancy I would recommend  to add a `/` in line 37 [1] after the tenant regex as:

```
location ~ ^/(?<t>tenant1|tenant2)/ {
```

instead of 

```
location ~ ^/(?<t>tenant1|tenant2) {
```

Otherwise the app works also with urls like `http://localhost:8080/tenant1abc/` and not only `http://localhost:8080/tenant1/`.

[1] https://github.com/qwc-services/qwc-services.github.io/blob/master/src/topics/MultiTenancy.md?plain=1#L37

**Comment by manisandro** [comment]
Thanks, done in https://github.com/qwc-services/qwc-services.github.io/commit/8552449bf5447d726ee86934b5e2870d2a5552cc
