### ISSUE TITLE
Find an Domain name reflecting the community project.

### ISSUE THREAD

**Issue by pka** [qwc-services/qwc-services.github.io#2]
Using QGIS in the domain needs discussion and "QWC" is somewhat cryptic. Ideas welcome!

**Comment by vpicavet** [comment]
qgis-web-client.org ?

It may require approval from QGIS PSC since there is "qgis" in the domain name. But since the project itself has qgis in its name, should be ok.

Other better suggestions welcome I think :-)

**Comment by pka** [comment]
I finally found out how to publish under the Github organisation URL https://qwc-services.github.io/! The repo requires a magic name, so existing cloned repos should be renamed with
`git remote set-url origin git@github.com:qwc-services/qwc-services.github.io.git`
